import type { AgendaItem, GalleryItem, NewsItem, PublicService, Statistic } from "@/types";

export const site = {
    name: "Kelurahan Tamansari",
    district: "Kecamatan Pulomerak",
    city: "Kota Cilegon",
    phone: "+62 851-3525-9609",
    email: "kelurahan.tamansari@cilegon.go.id",
    address: "Tamansari, Pulomerak, Kota Cilegon, Banten",
    wa: "https://wa.me/6285135259609",
};

export const statistics: Statistic[] = [
    { label: "Jumlah Penduduk", value: 12840 },
    { label: "Kartu Keluarga", value: 3420 },
    { label: "RT", value: 32 },
    { label: "RW", value: 8 },
    { label: "Surat Hari Ini", value: 47 },
    { label: "Pengaduan Aktif", value: 12 },
];

export const services: PublicService[] = [
    { id: "permohonan-legalisasi-dokumen", title: "PERMOHONAN LEGALISASI DOKUMEN", category: "administrasi", description: "Layanan administrasi kelurahan untuk permohonan legalisasi dokumen.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Permohonan legalisasi dokumen", channel: "Surat Online" },
    { id: "penandatangan-surat-kuasa-pensiun", title: "PENANDATANGAN SURAT KUASA KHUSUS UNTUK PEMBAYARAN PENSIUN", category: "administrasi", description: "Layanan administrasi kelurahan untuk penandatangan surat kuasa khusus untuk pembayaran pensiun.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penandatangan surat kuasa khusus untuk pembayaran pensiun", channel: "Surat Online" },
    { id: "pelimpahan-nomor-porsi-haji", title: "PENANDATANGAN SURAT KUASA PENUNJUKAN PELIMPAHAN NOMOR PORSI JEMAH HAJI MENINGGAL DUNIA", category: "administrasi", description: "Layanan administrasi kelurahan untuk penandatangan surat kuasa penunjukan pelimpahan nomor porsi jemah haji meninggal dunia.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penandatangan surat kuasa penunjukan pelimpahan nomor porsi jemah haji meninggal dunia", channel: "Surat Online" },
    { id: "persetujuan-orang-tua-tni", title: "PENANDATANGAN SURAT PERSETUJUAN ORANG TUA/WALI DAN DAFTAR RIWAYAT HIDUP PENDAFTARAN ANGGOTA TNI", category: "administrasi", description: "Layanan administrasi kelurahan untuk penandatangan surat persetujuan orang tua/wali dan daftar riwayat hidup pendaftaran anggota tni.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penandatangan surat persetujuan orang tua/wali dan daftar riwayat hidup pendaftaran anggota tni", channel: "Surat Online" },
    { id: "pernyataan-tidak-keberatan-pbg", title: "PENGESAHAN SURAT PERNYATAAN TIDAK KEBERATAN DALAM PENERBITAN PERSETUJUAN BANGUNAN GEDUNG/IZIN GANGGUAN", category: "administrasi", description: "Layanan administrasi kelurahan untuk pengesahan surat pernyataan tidak keberatan dalam penerbitan persetujuan bangunan gedung/izin gangguan.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Pengesahan surat pernyataan tidak keberatan dalam penerbitan persetujuan bangunan gedung/izin gangguan", channel: "Surat Online" },
    { id: "belum-memiliki-rumah", title: "PENERBITAN SURAT KETERANGAN BELUM MEMILIKI RUMAH", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat keterangan belum memiliki rumah.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat keterangan belum memiliki rumah", channel: "Surat Online" },
    { id: "belum-mempunyai-pekerjaan", title: "PENERBITAN SURAT KETERANGAN BELUM MEMPUNYAI PEKERJAAN", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat keterangan belum mempunyai pekerjaan.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat keterangan belum mempunyai pekerjaan", channel: "Surat Online" },
    { id: "belum-pernah-menikah", title: "PENERBITAN SURAT KETERANGAN BELUM PERNAH MENIKAH", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat keterangan belum pernah menikah.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat keterangan belum pernah menikah", channel: "Surat Online" },
    { id: "boro-kerja", title: "PENERBITAN SURAT KETERANGAN BORO KERJA", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat keterangan boro kerja.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat keterangan boro kerja", channel: "Surat Online" },
    { id: "domisili", title: "PENERBITAN SURAT KETERANGAN DOMISILI", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat keterangan domisili.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat keterangan domisili", channel: "Surat Online" },
    { id: "usaha", title: "PENERBITAN SURAT KETERANGAN USAHA", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat keterangan usaha.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat keterangan usaha", channel: "Surat Online" },
    { id: "ghaib", title: "PENERBITAN SURAT KETERANGAN GHAIB", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat keterangan ghaib.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat keterangan ghaib", channel: "Surat Online" },
    { id: "janda-duda", title: "PENERBITAN SURAT KETERANGAN JANDA/DUDA", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat keterangan janda/duda.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat keterangan janda/duda", channel: "Surat Online" },
    { id: "kebakaran", title: "PENERBITAN SURAT KETERANGAN KEBAKARAN", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat keterangan kebakaran.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat keterangan kebakaran", channel: "Surat Online" },
    { id: "kehilangan", title: "PENERBITAN SURAT KETERANGAN KEHILANGAN", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat keterangan kehilangan.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat keterangan kehilangan", channel: "Surat Online" },
    { id: "kelahiran", title: "PENERBITAN SURAT KETERANGAN KELAHIRAN", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat keterangan kelahiran.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat keterangan kelahiran", channel: "Surat Online" },
    { id: "berkelakuan-baik", title: "PENERBITAN SURAT PENGANTAR BERKELAKUAN BAIK", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat pengantar berkelakuan baik.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat pengantar berkelakuan baik", channel: "Surat Online" },
    { id: "kematian", title: "PENERBITAN SURAT KETERANGAN KEMATIAN", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat keterangan kematian.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat keterangan kematian", channel: "Surat Online" },
    { id: "letak-objek-tanah", title: "PENERBITAN SURAT KETERANGAN LETAK OBJEK TANAH", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat keterangan letak objek tanah.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat keterangan letak objek tanah", channel: "Surat Online" },
    { id: "pindah-datang", title: "PENERBITAN SURAT KETERANGAN PINDAH DATANG", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat keterangan pindah datang.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat keterangan pindah datang", channel: "Surat Online" },
    { id: "pindah-keluar", title: "PENERBITAN SURAT KETERANGAN PINDAH KELUAR", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat keterangan pindah keluar.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat keterangan pindah keluar", channel: "Surat Online" },
    { id: "tidak-mampu", title: "PENERBITAN SURAT KETERANGAN TIDAK MAMPU", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat keterangan tidak mampu.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat keterangan tidak mampu", channel: "Surat Online" },
    { id: "wali-nikah", title: "PENERBITAN SURAT KETERANGAN WALI NIKAH", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat keterangan wali nikah.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat keterangan wali nikah", channel: "Surat Online" },
    { id: "calon-pekerja-migran-indonesia", title: "PENERBITAN SURAT PENGANTAR CALON PEKERJA MIGRAN INDONESIA", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat pengantar calon pekerja migran indonesia.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat pengantar calon pekerja migran indonesia", channel: "Surat Online" },
    { id: "nikah-talak-cerai-rujuk", title: "PENERBITAN SURAT PENGANTAR NIKAH, TALAK, CERAI, RUJUK", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat pengantar nikah, talak, cerai, rujuk.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat pengantar nikah, talak, cerai, rujuk", channel: "Surat Online" },
    { id: "dispensasi-nikah", title: "PENERBITAN SURAT PENGANTAR PEMBUATAN DISPENSASI NIKAH", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat pengantar pembuatan dispensasi nikah.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat pengantar pembuatan dispensasi nikah", channel: "Surat Online" },
    { id: "konversi-tanah", title: "PENERBITAN SURAT PENGANTAR PEMBUATAN KONVERSI TANAH", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat pengantar pembuatan konversi tanah.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat pengantar pembuatan konversi tanah", channel: "Surat Online" },
    { id: "pernyataan-ahli-waris", title: "PENERBITAN SURAT PENGANTAR PEMBUATAN PERNYATAAN AHLI WARIS", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat pengantar pembuatan pernyataan ahli waris.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat pengantar pembuatan pernyataan ahli waris", channel: "Surat Online" },
    { id: "skck", title: "PENERBITAN SURAT PENGANTAR PEMBUATAN SURAT KETERANGAN CATATAN KEPOLISIAN", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat pengantar pembuatan surat keterangan catatan kepolisian.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat pengantar pembuatan surat keterangan catatan kepolisian", channel: "Surat Online" },
    { id: "duplikat-surat-nikah", title: "PENERBITAN SURAT PENGANTAR PENERBITAN DUPLIKAT SURAT NIKAH", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat pengantar penerbitan duplikat surat nikah.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat pengantar penerbitan duplikat surat nikah", channel: "Surat Online" },
    { id: "kartu-keluarga", title: "PENERBITAN SURAT PENGANTAR PENERBITAN KARTU KELUARGA", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat pengantar penerbitan kartu keluarga.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat pengantar penerbitan kartu keluarga", channel: "Surat Online" },
    { id: "kartu-tanda-penduduk", title: "PENERBITAN SURAT PENGANTAR PENERBITAN KARTU TANDA PENDUDUK", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat pengantar penerbitan kartu tanda penduduk.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat pengantar penerbitan kartu tanda penduduk", channel: "Surat Online" },
    { id: "ijin-kegiatan-keramaian", title: "PENERBITAN SURAT REKOMENDASI IJIN KEGIATAN / KERAMAIAN", category: "administrasi", description: "Layanan administrasi kelurahan untuk penerbitan surat rekomendasi ijin kegiatan / keramaian.", requirements: ["KTP", "KK", "Surat pengantar RT/RW", "Dokumen pendukung"], online: true, legalBasis: "Standar pelayanan administrasi Kelurahan Tamansari", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit dokumen"], output: "Penerbitan surat rekomendasi ijin kegiatan / keramaian", channel: "Surat Online" },
];

export const news: NewsItem[] = [
    { id: "1", title: "Transformasi Pelayanan Digital Tamansari", category: "Pemerintahan", excerpt: "Kelurahan mempercepat layanan surat, pengaduan, dan POSBANKUM berbasis kanal digital.", date: "2026-08-02", image: "/assets/berita-1.jpg" },
    { id: "2", title: "Kegiatan Kebersihan Lingkungan RW", category: "Lingkungan", excerpt: "Kolaborasi warga memperkuat lingkungan bersih, sehat, dan responsif terhadap aduan.", date: "2026-07-28", image: "/assets/berita-2.jpg" },
    { id: "3", title: "Sosialisasi Bantuan Hukum Warga", category: "POSBANKUM", excerpt: "Warga dapat melakukan booking konsultasi awal melalui kanal layanan resmi.", date: "2026-07-20", image: "/assets/berita-3.jpg" },
];

export const agenda: AgendaItem[] = [
    { id: "a1", title: "Pelayanan Administrasi Keliling", date: "2026-08-06", location: "Balai RW 03", reminder: true },
    { id: "a2", title: "Konsultasi POSBANKUM", date: "2026-08-09", location: "Kantor Kelurahan", reminder: true },
];

export const gallery: GalleryItem[] = [1, 2, 3, 4, 5, 6].map((n) => ({ id: String(n), title: `Dokumentasi Tamansari ${n}`, type: "photo", src: `/assets/galeri-${n}.jpg` }));
