import type { AgendaItem, GalleryItem, NewsItem, PublicService, Statistic } from "@/types";

export const site = {
    name: "Kelurahan Tamansari",
    district: "Kecamatan Pulomerak",
    city: "Kota Cilegon",
    phone: "+62 851-3525-9609",
    email: "kelurahan.tamansari@cilegon.go.id",
    address: "Tamansari, Pulomerak, Kota Cilegon, Banten",
    wa: "https://wa.me/6285135259609",
};

export const statistics: Statistic[] = [
    { label: "Jumlah Penduduk", value: 12840 },
    { label: "Kartu Keluarga", value: 3420 },
    { label: "RT", value: 32 },
    { label: "RW", value: 8 },
    { label: "Surat Hari Ini", value: 47 },
    { label: "Pengaduan Aktif", value: 12 },
];

export const services: PublicService[] = [
    { id: "domisili", title: "Surat Keterangan Domisili", category: "administrasi", description: "Bukti keterangan tempat tinggal untuk kebutuhan sekolah, kerja, dan administrasi umum.", requirements: ["KTP", "KK", "Formulir pengajuan"], online: true, legalBasis: "Peraturan pelayanan administrasi kelurahan", flow: ["Isi formulir", "Unggah berkas", "Verifikasi petugas", "Terbit surat"], output: "Surat keterangan domisili", channel: "Surat Online" },
    { id: "kartu-keluarga", title: "Surat Pengantar Kartu Keluarga", category: "administrasi", description: "Pengantar perubahan data KK, penambahan anggota, dan pembaruan administrasi keluarga.", requirements: ["KTP", "KK lama", "Dokumen pendukung"], online: true, legalBasis: "Standar layanan administrasi kependudukan", flow: ["Ajukan permohonan", "Verifikasi data", "Cetak pengantar", "Ambil dokumen"], output: "Surat pengantar KK", channel: "Surat Online" },
    { id: "ktp", title: "Surat Pengantar KTP", category: "administrasi", description: "Pengantar layanan KTP untuk pemula, perubahan data, dan penggantian dokumen.", requirements: ["KTP lama jika ada", "KK", "Foto pendukung"], online: true, legalBasis: "Layanan administrasi kependudukan kelurahan", flow: ["Unggah dokumen", "Verifikasi petugas", "Cetak pengantar", "Selesai"], output: "Surat pengantar KTP", channel: "Surat Online" },
    { id: "kelahiran", title: "Surat Pengantar Kelahiran", category: "administrasi", description: "Pengantar untuk pencatatan kelahiran dan pembaruan data keluarga.", requirements: ["KTP orang tua", "KK", "Surat keterangan lahir"], online: true, legalBasis: "Standar pencatatan sipil", flow: ["Submit berkas", "Validasi data", "Proses petugas", "Dokumen diterbitkan"], output: "Surat pengantar kelahiran", channel: "Surat Online" },
    { id: "kematian", title: "Surat Keterangan Kematian", category: "administrasi", description: "Dokumen pengantar untuk pencatatan peristiwa kematian warga.", requirements: ["KTP pelapor", "KK", "Surat keterangan RT/RW"], online: true, legalBasis: "Standar administrasi pencatatan sipil", flow: ["Ajukan data", "Cek validitas", "Terbit surat", "Serahkan ke warga"], output: "Surat keterangan kematian", channel: "Surat Online" },
    { id: "nikah", title: "Surat Pengantar Nikah", category: "administrasi", description: "Pengantar administrasi untuk kebutuhan pencatatan pernikahan warga.", requirements: ["KTP calon pengantin", "KK", "Dokumen pendukung"], online: true, legalBasis: "Layanan administrasi pernikahan", flow: ["Input data", "Verifikasi berkas", "Persetujuan petugas", "Terbit surat"], output: "Surat pengantar nikah", channel: "Surat Online" },
    { id: "usaha", title: "Surat Keterangan Usaha", category: "administrasi", description: "Bukti usaha warga untuk perbankan, perizinan, dan keperluan resmi lain.", requirements: ["KTP", "KK", "Foto tempat usaha"], online: true, legalBasis: "Standar layanan usaha mikro", flow: ["Ajukan usaha", "Verifikasi lokasi", "Finalisasi data", "Terbit surat"], output: "Surat keterangan usaha", channel: "Surat Online" },
    { id: "pindah", title: "Surat Pengantar Pindah", category: "administrasi", description: "Pengantar perpindahan domisili antar wilayah administrasi.", requirements: ["KTP", "KK", "Alamat tujuan"], online: true, legalBasis: "Layanan administrasi kepindahan", flow: ["Isi data pindah", "Periksa dokumen", "Otorisasi", "Terbit surat"], output: "Surat pengantar pindah", channel: "Surat Online" },
    { id: "datang", title: "Surat Keterangan Datang", category: "administrasi", description: "Pengantar untuk warga yang baru menetap di wilayah Tamansari.", requirements: ["KTP", "KK", "Surat pindah dari asal"], online: true, legalBasis: "Layanan administrasi penduduk datang", flow: ["Unggah dokumen", "Cek asal wilayah", "Verifikasi", "Terbit surat"], output: "Surat keterangan datang", channel: "Surat Online" },
    { id: "sktm", title: "Surat Keterangan Tidak Mampu", category: "administrasi", description: "Bukti keterangan sosial ekonomi untuk pendidikan, kesehatan, dan bantuan sosial.", requirements: ["KTP", "KK", "Surat pengantar RT/RW"], online: true, legalBasis: "Standar bantuan sosial daerah", flow: ["Ajukan permohonan", "Survey/verifikasi", "Validasi petugas", "Terbit surat"], output: "Surat keterangan tidak mampu", channel: "Surat Online" },
    { id: "domisili-usaha", title: "Surat Keterangan Domisili Usaha", category: "administrasi", description: "Pengantar untuk kebutuhan legalitas usaha skala kecil dan mikro.", requirements: ["KTP", "KK", "Foto usaha"], online: true, legalBasis: "Layanan administrasi usaha", flow: ["Masukkan data", "Validasi lokasi", "Terbit surat", "Selesai"], output: "Surat domisili usaha", channel: "Surat Online" },
    { id: "domisili-ormas", title: "Surat Keterangan Domisili Ormas", category: "administrasi", description: "Pengantar legalitas domisili organisasi kemasyarakatan di wilayah kelurahan.", requirements: ["SK organisasi", "KTP pengurus", "Alamat sekretariat"], online: true, legalBasis: "Administrasi organisasi kemasyarakatan", flow: ["Upload data", "Verifikasi sekretariat", "Persetujuan", "Terbit surat"], output: "Surat domisili ormas", channel: "Surat Online" },
    { id: "domisili-sekolah", title: "Surat Keterangan Domisili Sekolah", category: "administrasi", description: "Pengantar bagi lembaga pendidikan yang berkedudukan di wilayah Tamansari.", requirements: ["Izin sekolah", "Alamat lembaga", "Identitas penanggung jawab"], online: true, legalBasis: "Administrasi lembaga pendidikan", flow: ["Ajukan data", "Verifikasi lokasi", "Pengesahan", "Terbit surat"], output: "Surat domisili sekolah", channel: "Surat Online" },
    { id: "domisili-yayasan", title: "Surat Keterangan Domisili Yayasan", category: "administrasi", description: "Dokumen pengantar untuk yayasan yang berdomisili di wilayah kelurahan.", requirements: ["Akta yayasan", "KTP pengurus", "Alamat kantor"], online: true, legalBasis: "Administrasi badan hukum sosial", flow: ["Input berkas", "Cek dokumen", "Verifikasi petugas", "Terbit surat"], output: "Surat domisili yayasan", channel: "Surat Online" },
    { id: "domisili-masjid", title: "Surat Keterangan Domisili Rumah Ibadah", category: "administrasi", description: "Pengantar legalitas domisili tempat ibadah di lingkungan warga.", requirements: ["Data pengelola", "Alamat rumah ibadah", "Foto lokasi"], online: true, legalBasis: "Administrasi rumah ibadah", flow: ["Unggah data", "Koordinasi lingkungan", "Validasi", "Terbit surat"], output: "Surat domisili rumah ibadah", channel: "Surat Online" },
    { id: "kurang-mampu", title: "Surat Keterangan Kurang Mampu", category: "administrasi", description: "Surat sosial ekonomi untuk keperluan layanan pendidikan dan kesehatan.", requirements: ["KTP", "KK", "Keterangan RT/RW"], online: true, legalBasis: "Kebijakan layanan sosial kelurahan", flow: ["Input data", "Survey data", "Verifikasi", "Terbit surat"], output: "Surat keterangan kurang mampu", channel: "Surat Online" },
    { id: "belum-menikah", title: "Surat Keterangan Belum Menikah", category: "administrasi", description: "Dokumen pengantar untuk kebutuhan administrasi pernikahan dan pekerjaan.", requirements: ["KTP", "KK", "Surat pernyataan"], online: true, legalBasis: "Layanan administrasi kependudukan", flow: ["Ajukan data", "Validasi identitas", "Persetujuan petugas", "Terbit surat"], output: "Surat belum menikah", channel: "Surat Online" },
    { id: "belum-punya-kk", title: "Surat Keterangan Belum Memiliki KK", category: "administrasi", description: "Keterangan bagi warga yang membutuhkan pencatatan keluarga baru.", requirements: ["KTP", "Surat pengantar RT/RW", "Dokumen keluarga"], online: true, legalBasis: "Layanan administrasi keluarga", flow: ["Submit permohonan", "Cek data", "Verifikasi", "Terbit surat"], output: "Surat belum memiliki KK", channel: "Surat Online" },
    { id: "pindah-datang", title: "Surat Keterangan Pindah Datang", category: "administrasi", description: "Layanan bagi warga yang pindah masuk dan membutuhkan pengantar resmi.", requirements: ["KTP", "KK", "Surat pindah asal"], online: true, legalBasis: "Administrasi penduduk pindah datang", flow: ["Ajukan formulir", "Cek asal", "Validasi", "Terbit surat"], output: "Surat pindah datang", channel: "Surat Online" },
    { id: "ahli-waris", title: "Surat Keterangan Ahli Waris", category: "administrasi", description: "Pengantar untuk kebutuhan administrasi waris dan legalitas keluarga.", requirements: ["KTP ahli waris", "KK", "Dokumen pendukung"], online: true, legalBasis: "Administrasi surat keterangan keluarga", flow: ["Unggah data ahli waris", "Verifikasi keluarga", "Pengesahan", "Terbit surat"], output: "Surat keterangan ahli waris", channel: "Surat Online" },
    { id: "tidak-sengketa", title: "Surat Keterangan Tidak Sengketa", category: "administrasi", description: "Keterangan untuk keperluan tanah, aset, dan administrasi umum.", requirements: ["KTP", "Bukti kepemilikan", "Pengantar lingkungan"], online: true, legalBasis: "Administrasi pertanahan kelurahan", flow: ["Input permohonan", "Verifikasi lokasi", "Pengesahan", "Terbit surat"], output: "Surat tidak sengketa", channel: "Surat Online" },
    { id: "kehilangan", title: "Surat Keterangan Kehilangan", category: "administrasi", description: "Dokumen pengantar untuk kehilangan dokumen pribadi atau barang penting.", requirements: ["KTP", "Kronologi kehilangan", "Bukti pendukung"], online: true, legalBasis: "Administrasi keterangan kehilangan", flow: ["Laporkan kehilangan", "Validasi kronologi", "Terbit surat", "Selesai"], output: "Surat keterangan kehilangan", channel: "Surat Online" },
    { id: "cerai", title: "Surat Keterangan Cerai", category: "administrasi", description: "Pengantar untuk kebutuhan administrasi status perkawinan.", requirements: ["KTP", "KK", "Dokumen pendukung"], online: true, legalBasis: "Administrasi status keluarga", flow: ["Ajukan data", "Cek status", "Verifikasi", "Terbit surat"], output: "Surat keterangan cerai", channel: "Surat Online" },
    { id: "rekomendasi-bansos", title: "Surat Rekomendasi Bantuan Sosial", category: "administrasi", description: "Rekomendasi pengantar untuk akses program bantuan sosial resmi.", requirements: ["KTP", "KK", "Keterangan sosial"], online: true, legalBasis: "Administrasi bantuan sosial", flow: ["Pengajuan", "Verifikasi sosial", "Persetujuan", "Terbit surat"], output: "Surat rekomendasi bansos", channel: "Surat Online" },
    { id: "rekomendasi-sekolah", title: "Surat Rekomendasi Sekolah", category: "administrasi", description: "Pengantar untuk kebutuhan sekolah, beasiswa, atau administrasi pendidikan.", requirements: ["KTP wali", "KK", "Bukti sekolah"], online: true, legalBasis: "Administrasi pendidikan warga", flow: ["Ajukan data", "Verifikasi", "Otorisasi", "Terbit surat"], output: "Surat rekomendasi sekolah", channel: "Surat Online" },
    { id: "permohonan-rt-rw", title: "Surat Pengantar RT/RW", category: "administrasi", description: "Layanan pengantar dari lingkungan sebelum diverifikasi kelurahan.", requirements: ["KTP", "Data tujuan", "Surat dari RT/RW"], online: true, legalBasis: "Koordinasi lingkungan kelurahan", flow: ["Isi kebutuhan", "Koordinasi RT/RW", "Verifikasi kelurahan", "Terbit surat"], output: "Surat pengantar RT/RW", channel: "Surat Online" },
    { id: "informasi-warga", title: "Surat Keterangan Informasi Warga", category: "administrasi", description: "Dokumen keterangan umum untuk keperluan administrasi non-spesifik.", requirements: ["KTP", "KK", "Keperluan administrasi"], online: true, legalBasis: "Administrasi umum kelurahan", flow: ["Ajukan kebutuhan", "Validasi", "Persetujuan", "Terbit surat"], output: "Surat keterangan informasi warga", channel: "Surat Online" },
    { id: "pengaduan", title: "Pengaduan Masyarakat", category: "pengaduan", description: "Kirim laporan dengan foto, lokasi, QR tiket, dan tracking progres.", requirements: ["Identitas pelapor", "Deskripsi", "Foto/lokasi opsional"], online: true, legalBasis: "Standar layanan pengaduan publik", flow: ["Kirim laporan", "Nomor tiket dibuat", "Diproses petugas", "Selesai"], output: "Tiket pengaduan", channel: "Portal Pengaduan" },
    { id: "posbankum", title: "POSBANKUM", category: "posbankum", description: "Booking konsultasi hukum, nomor antrian, dan tracking hasil konsultasi.", requirements: ["Identitas", "Topik konsultasi"], online: true, legalBasis: "Layanan bantuan hukum warga", flow: ["Pilih jadwal", "Isi topik", "Konfirmasi petugas", "Konsultasi"], output: "Nomor antrian konsultasi", channel: "POSBANKUM" },
];

export const news: NewsItem[] = [
    { id: "1", title: "Transformasi Pelayanan Digital Tamansari", category: "Pemerintahan", excerpt: "Kelurahan mempercepat layanan surat, pengaduan, dan POSBANKUM berbasis kanal digital.", date: "2026-08-02", image: "/assets/berita-1.jpg" },
    { id: "2", title: "Kegiatan Kebersihan Lingkungan RW", category: "Lingkungan", excerpt: "Kolaborasi warga memperkuat lingkungan bersih, sehat, dan responsif terhadap aduan.", date: "2026-07-28", image: "/assets/berita-2.jpg" },
    { id: "3", title: "Sosialisasi Bantuan Hukum Warga", category: "POSBANKUM", excerpt: "Warga dapat melakukan booking konsultasi awal melalui kanal layanan resmi.", date: "2026-07-20", image: "/assets/berita-3.jpg" },
];

export const agenda: AgendaItem[] = [
    { id: "a1", title: "Pelayanan Administrasi Keliling", date: "2026-08-06", location: "Balai RW 03", reminder: true },
    { id: "a2", title: "Konsultasi POSBANKUM", date: "2026-08-09", location: "Kantor Kelurahan", reminder: true },
];

export const gallery: GalleryItem[] = [1, 2, 3, 4, 5, 6].map((n) => ({ id: String(n), title: `Dokumentasi Tamansari ${n}`, type: "photo", src: `/assets/galeri-${n}.jpg` }));