"use client";
import { useEffect, useRef, useState, type ChangeEvent, type ReactNode } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { useWargaAuth } from "@/components/auth/warga-auth-provider";
import { createSubmission, uploadSubmissionAttachment } from "@/services/surat-online.service";
import { getServiceStatement } from "@/services/submission-trust";
import { compressWargaFile, MAX_WARGA_FILE_SIZE } from "@/services/warga-file-compress";
import { getMarriageDayName, MARRIAGE_SERVICE_ID, MARRIAGE_SERVICE_NAME, MARRIAGE_STEPS, validateMarriageAdditionalData, validateMarriageStep } from "@/services/marriage-submission";
import { createSubmissionDraft, readSubmissionDraft, submissionDraftKey, writeSubmissionDraft, type SubmissionDraft } from "@/services/submission-memory";
import { getMySubmittedMemory } from "@/services/warga-pengajuan.service";

type Data = Record<string, any>;
const css = "min-h-12 w-full rounded-2xl border bg-white px-4 font-bold";
const person = { nama_lengkap:"",nik:"",nomor_kk:"",jenis_kelamin:"",tempat_lahir:"",tanggal_lahir:"",kewarganegaraan:"Indonesia",agama:"",pekerjaan:"",alamat:"",rt:"",rw:"",kelurahan:"",kecamatan:"",status_perkawinan:"" };
const parent = (jenis_kelamin:string) => ({ status:"Masih hidup",nama_lengkap:"",nik:"",jenis_kelamin,tempat_lahir:"",tanggal_lahir:"",kewarganegaraan:"Indonesia",agama:"",pekerjaan:"",alamat:"" });
const docs = [["KTP",true],["KK",true],["Akta kelahiran",false],["Pasfoto",false],["Persetujuan calon pengantin",false],["Dokumen orang tua/wali",false],["Dokumen lain yang dipersyaratkan KUA",false]] as const;
function F({label,children}:{label:string;children:ReactNode}){return <label className="block"><b className="mb-2 block">{label}</b>{children}</label>}
function I({label,v,set,type="text",optional=false}:{label:string;v:string;set:(x:string)=>void;type?:string;optional?:boolean}){return <F label={`${label}${optional?"":" *"}`}><input className={css} type={type} value={v} onChange={e=>set(e.target.value)}/></F>}
function S({label,v,set,values}:{label:string;v:string;set:(x:string)=>void;values:string[]}){return <F label={`${label} *`}><select className={css} value={v} onChange={e=>set(e.target.value)}><option value="">Pilih</option>{values.map(x=><option key={x}>{x}</option>)}</select></F>}
function Person({data,set}:{data:Data;set:(x:Data)=>void}){const u=(k:string)=>(v:string)=>set({...data,[k]:v});return <div className="grid gap-4 md:grid-cols-2"><I label="Nama lengkap" v={data.nama_lengkap} set={u("nama_lengkap")}/><I label="NIK" v={data.nik} set={u("nik")}/><I label="Nomor KK" v={data.nomor_kk} set={u("nomor_kk")}/><S label="Jenis kelamin" v={data.jenis_kelamin} set={u("jenis_kelamin")} values={["Laki-laki","Perempuan"]}/><I label="Tempat lahir" v={data.tempat_lahir} set={u("tempat_lahir")}/><I label="Tanggal lahir" type="date" v={data.tanggal_lahir} set={u("tanggal_lahir")}/><I label="Kewarganegaraan" v={data.kewarganegaraan} set={u("kewarganegaraan")}/><I label="Agama" v={data.agama} set={u("agama")}/><I label="Pekerjaan" v={data.pekerjaan} set={u("pekerjaan")}/><I label="Alamat" v={data.alamat} set={u("alamat")}/><I label="RT" v={data.rt} set={u("rt")}/><I label="RW" v={data.rw} set={u("rw")}/><I label="Kelurahan" v={data.kelurahan} set={u("kelurahan")}/><I label="Kecamatan" v={data.kecamatan} set={u("kecamatan")}/><I label="Status perkawinan" v={data.status_perkawinan} set={u("status_perkawinan")}/></div>}
function Parent({title,data,set}:{title:string;data:Data;set:(x:Data)=>void}){const u=(k:string)=>(v:string)=>set({...data,[k]:v}), optional=data.status==="Tidak diketahui";return <section className="rounded-3xl border p-5"><h3 className="text-xl font-black">{title}</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><S label="Status" v={data.status} set={u("status")} values={["Masih hidup","Meninggal dunia","Tidak diketahui"]}/>{[["Nama lengkap","nama_lengkap"],["NIK","nik"],["Tempat lahir","tempat_lahir"],["Tanggal lahir","tanggal_lahir"],["Kewarganegaraan","kewarganegaraan"],["Agama","agama"],["Pekerjaan","pekerjaan"],["Alamat","alamat"]].map(([l,k])=><I key={k} label={l} v={data[k]} set={u(k)} type={k==="tanggal_lahir"?"date":"text"} optional={optional||k==="nik"||k==="tanggal_lahir"}/>)}</div>{data.status==="Meninggal dunia"&&<p className="mt-3 text-sm font-bold">Nama dapat ditulis: NGASIMIN (ALM).</p>}</section>}
function ReviewRows({rows}:{rows:Array<[string,unknown]>}){return <dl className="grid gap-3 text-sm">{rows.map(([label,value])=><div key={label} className="grid min-w-0 gap-1 sm:grid-cols-[140px_1fr]"><dt className="font-black text-slate-500">{label}</dt><dd className="min-w-0 break-words font-bold">{String(value||"Belum diisi")}</dd></div>)}</dl>}
function ReviewCard({title,step,edit,wide=false,children}:{title:string;step?:number;edit?:(step:number)=>void;wide?:boolean;children:ReactNode}){return <section className={`min-w-0 rounded-2xl border bg-white p-5 shadow-sm ${wide?"lg:col-span-2":""}`}><div className="mb-4 flex items-start justify-between gap-3"><h3 className="text-lg font-black">{title}</h3>{step&&edit?<button type="button" onClick={()=>edit(step)} className="min-h-11 shrink-0 rounded-xl border px-4 text-sm font-black text-gov-900">EDIT</button>:null}</div>{children}</section>}

export function MarriageSubmissionForm(){
 const router=useRouter(),{user,profile}=useWargaAuth(); const [step,setStep]=useState(1),[error,setError]=useState(""),[busy,setBusy]=useState(false),[consent,setConsent]=useState(false);
 const [nikah,setNikah]=useState<Data>({jenis_permohonan:"NIKAH",hari_akad:"",tanggal_akad:"",jam_akad:"",tempat_akad:"",kua_tujuan:"",mas_kawin:"",cara_pembayaran_mas_kawin:"",membutuhkan_isbat:false});
 const [pasangan,setPasangan]=useState<Data>({...person}),[ayah,setAyah]=useState<Data>(parent("Laki-laki")),[ibu,setIbu]=useState<Data>(parent("Perempuan")),[wali,setWali]=useState<Data>({nama_lengkap:"",nik:"",hubungan:"",alamat:"",nomor_hp:""});
 const [berkas,setBerkas]=useState<Array<{jenis:string;wajib:boolean;file?:File;originalSize?:number;processing?:boolean;preview?:string;error?:string}>>(docs.map(([jenis,wajib])=>({jenis,wajib})));
 const [draft,setDraft]=useState<SubmissionDraft<Data>|null>(null),[memory,setMemory]=useState<Data|null>(null),[ready,setReady]=useState(false),[saveState,setSaveState]=useState("");
 const cameraInputs=useRef<Array<HTMLInputElement|null>>([]), fileInputs=useRef<Array<HTMLInputElement|null>>([]);
 useEffect(()=>()=>{berkas.forEach(x=>{if(x.preview)URL.revokeObjectURL(x.preview)})},[berkas]);
  const statement=getServiceStatement(MARRIAGE_SERVICE_NAME).statement, raw=()=>({nikah,pasangan,orang_tua:{ayah,ibu},wali,dokumen:berkas.map(x=>({jenis:x.jenis,wajib:x.wajib,status:x.file?"TERSEDIA":"BELUM TERSEDIA",nama_file:x.file?.name})),pernyataan:{teks:statement,disetujui:consent}});
  const draftKey=user?submissionDraftKey(user.id,MARRIAGE_SERVICE_ID):"";
  useEffect(()=>{if(!user)return;setDraft(readSubmissionDraft<Data>(localStorage,submissionDraftKey(user.id,MARRIAGE_SERVICE_ID)));void getMySubmittedMemory(MARRIAGE_SERVICE_ID).then(x=>setMemory(x as Data|null)).catch(()=>setMemory(null))},[user]);
  useEffect(()=>{if(!ready||!draftKey)return;setSaveState("Menyimpan...");const timer=window.setTimeout(()=>{try{const metadata=berkas.filter(x=>x.file).map(x=>({jenis:x.jenis,wajib:x.wajib,nama_file:x.file?.name,ukuran:x.file?.size,status:"PERLU_UPLOAD_ULANG" as const}));const saved=createSubmissionDraft(step,{nikah,pasangan,orang_tua:{ayah,ibu},wali,consent},metadata);writeSubmissionDraft(localStorage,draftKey,saved);setSaveState("Draft tersimpan")}catch{setSaveState("")}},600);return()=>window.clearTimeout(timer)},[ready,draftKey,step,nikah,pasangan,ayah,ibu,wali,consent,berkas]);
  function applyData(data:Data,currentStep=1){const n=data.nikah??{},parents=data.orang_tua??{};setNikah({...nikah,...n,hari_akad:getMarriageDayName(n.tanggal_akad)});setPasangan({...person,...(data.pasangan??{})});setAyah({...parent("Laki-laki"),...(parents.ayah??{})});setIbu({...parent("Perempuan"),...(parents.ibu??{})});setWali({nama_lengkap:"",nik:"",hubungan:"",alamat:"",nomor_hp:"",...(data.wali??{})});setConsent(data.consent===true);setStep(Math.min(8,Math.max(1,currentStep)));setReady(true)}
  function continueDraft(){if(!draft)return;applyData(draft.data,draft.currentStep);setBerkas(docs.map(([jenis,wajib])=>({jenis,wajib,error:draft.documents.some(x=>x.jenis===jenis)?"Dokumen sebelumnya belum tersedia di sesi ini. Silakan upload kembali.":undefined})));setDraft(null)}
  function startEmpty(){if(draftKey)localStorage.removeItem(draftKey);setDraft(null);setReady(true)}
  function useMemory(){const n=memory?.nikah??{};applyData({...memory,nikah:{...n,tanggal_akad:"",hari_akad:""},consent:false});setMemory(null)}
  function valid(s:number){try{if(s===1&&!profile?.nik)throw Error("Profil warga belum lengkap.");if(s>=2&&s<=4)validateMarriageStep(raw(),s);if(s===5&&berkas.some(x=>x.wajib&&!x.file))throw Error("KTP dan KK wajib tersedia.");if(s===6&&!consent)throw Error("Consent wajib diberikan.");setError("");return true}catch(e){setError(e instanceof Error?e.message:"Data belum lengkap.");return false}}
  async function file(i:number,e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];e.target.value="";if(!f)return;const allowed=["application/pdf","image/jpeg","image/jpg","image/png","image/webp"];if(!allowed.includes(f.type)){setError("Format file tidak didukung.");return}if(f.type==="application/pdf"&&f.size>MAX_WARGA_FILE_SIZE){setError("Ukuran PDF maksimal 1 MB.");return}setError("");setBerkas(x=>x.map((v,n)=>n===i?{...v,processing:true,error:undefined,originalSize:f.size}:v));try{const processed=await compressWargaFile(f);if(processed.size>MAX_WARGA_FILE_SIZE)throw new Error("Ukuran file setelah pemrosesan masih lebih dari 1 MB. Silakan gunakan foto dengan resolusi lebih rendah.");const preview=processed.type.startsWith("image/")?URL.createObjectURL(processed):undefined;setBerkas(x=>x.map((v,n)=>n===i?{...v,file:processed,processing:false,preview}:v))}catch(err){setBerkas(x=>x.map((v,n)=>n===i?{...v,processing:false,error:err instanceof Error&&err.message.includes("PDF")?err.message:"Foto tidak dapat diproses. Silakan ambil foto kembali."}:v));setError("")}}
  async function submit(){if(!valid(6)||busy)return;if(!user||!profile?.nik){setError("Data NIK belum tersedia pada profil. Silakan lengkapi profil terlebih dahulu.");router.push("/dashboard/profil");return}if(!/^\d{16}$/.test(profile.nik)){setError("Data NIK pada profil tidak valid. Silakan lengkapi profil terlebih dahulu.");router.push("/dashboard/profil");return}setBusy(true);const uploaded:Data[]=[];try{for(const [i,x]of berkas.entries())if(x.file){const up=await uploadSubmissionAttachment("pendukung",x.file,profile.nik,`draft-nikah-${Date.now()}-${i}`);uploaded.push({...x,path:up.path})}const additional=validateMarriageAdditionalData({...raw(),dokumen:uploaded.map(x=>({jenis:x.jenis,wajib:x.wajib,status:"TERSEDIA",nama_file:x.file.name,path:x.path}))});const payload={layanan_id:MARRIAGE_SERVICE_ID,nik:profile.nik,nama_lengkap:profile.nama_lengkap,nomor_kk:profile.nomor_kk,tempat_lahir:profile.tempat_lahir,tanggal_lahir:profile.tanggal_lahir,jenis_kelamin:profile.jenis_kelamin??"",agama:profile.agama??"",status_perkawinan:profile.status_perkawinan??"",status_pekerjaan:profile.status_pekerjaan??"",alamat:profile.alamat??"",rt_rw:`${profile.rt??""}/${profile.rw??""}`,kelurahan:profile.kelurahan??"",kecamatan:profile.kecamatan??"",nomor_hp:profile.nomor_hp??"",email:profile.email??"",jenis_surat:MARRIAGE_SERVICE_NAME,keperluan:`Pengantar NIKAH ke ${nikah.kua_tujuan}`,catatan:"",additional_data:additional,file_ktp:uploaded.find(x=>x.jenis==="KTP")?.path,file_kk:uploaded.find(x=>x.jenis==="KK")?.path,file_pendukung:uploaded.find(x=>x.jenis!=="KTP"&&x.jenis!=="KK")?.path??null,consent:true};await createSubmission(payload);if(draftKey)localStorage.removeItem(draftKey);alert("Pengajuan berhasil dikirim.");router.push("/dashboard/pengajuan")}catch(e){setError(e instanceof Error?e.message:"Gagal mengirim pengajuan.")}finally{setBusy(false)}}
  const setN=(k:string)=>(v:string)=>setNikah(k==="tanggal_akad"?{...nikah,tanggal_akad:v,hari_akad:getMarriageDayName(v)}:{...nikah,[k]:v}), setW=(k:string)=>(v:string)=>setWali({...wali,[k]:v}); const profileRows=[["Nama",profile?.nama_lengkap],["NIK",profile?.nik],["Nomor KK",profile?.nomor_kk],["Tempat/Tanggal Lahir",`${profile?.tempat_lahir||"-"}, ${profile?.tanggal_lahir||"-"}`],["Jenis kelamin",profile?.jenis_kelamin],["Agama",profile?.agama],["Status perkawinan",profile?.status_perkawinan],["Pekerjaan",profile?.status_pekerjaan],["Alamat",profile?.alamat],["RT/RW",`${profile?.rt||"-"}/${profile?.rw||"-"}`],["Kelurahan/Kecamatan",`${profile?.kelurahan||"-"}/${profile?.kecamatan||"-"}`],["Nomor HP",profile?.nomor_hp],["Email",profile?.email]];
 return <main className="min-h-screen bg-slate-50 px-4 py-28"><section className="mx-auto max-w-5xl rounded-[28px] bg-white p-6 shadow-xl"><Button type="button" variant="glass" onClick={()=>router.push("/dashboard/pengajuan")}>← Kembali ke Dashboard</Button><h1 className="mt-5 text-3xl font-black">PENERBITAN SURAT PENGANTAR NIKAH</h1>{!ready&&<div className="mt-5 grid gap-3 rounded-2xl border bg-slate-50 p-4"><b>{draft?"DRAFT PENGAJUAN DITEMUKAN":"Mulai pengajuan baru"}</b>{draft&&<><span>Terakhir disimpan: {new Date(draft.savedAt).toLocaleString("id-ID")}</span><div className="flex flex-wrap gap-2"><Button type="button" onClick={continueDraft}>LANJUTKAN DRAFT</Button><Button type="button" variant="glass" onClick={startEmpty}>MULAI DARI AWAL</Button></div></>}{!draft&&<Button type="button" onClick={startEmpty}>MULAI PENGAJUAN BARU</Button>}</div>}{ready&&memory&&<div className="mt-5 grid gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><b>DATA PENGAJUAN SEBELUMNYA TERSEDIA</b><span>Beberapa data dari pengajuan sebelumnya dapat digunakan.</span><div className="flex flex-wrap gap-2"><Button type="button" onClick={useMemory}>GUNAKAN DATA SEBELUMNYA</Button><Button type="button" variant="glass" onClick={()=>setMemory(null)}>MULAI DENGAN DATA KOSONG</Button></div></div>}{ready&&saveState&&<p className="mt-3 text-xs font-bold text-slate-500">{saveState}</p>}<div className="my-6 grid grid-cols-2 gap-2 md:grid-cols-4 lg:grid-cols-8">{MARRIAGE_STEPS.map((x,i)=><button key={x} disabled={i+1>step} onClick={()=>setStep(i+1)} className={`rounded-xl p-2 text-xs font-black ${i+1===step?"bg-gov-950 text-white":"bg-slate-100"}`}>{i+1}. {x}</button>)}</div>{error&&<p className="mb-5 rounded-xl bg-red-50 p-4 font-bold text-red-700">{error}</p>}
 {step===1&&<div><div className="flex justify-between"><h2 className="text-2xl font-black">DATA PEMOHON</h2><Link href="/dashboard/profil" className="font-black underline">UBAH PROFIL</Link></div><p className="text-emerald-700">Read-only dari profile warga.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{profileRows.map(([a,b])=><div className="rounded-xl bg-slate-50 p-3" key={a}><b>{a}</b><p>{b||"-"}</p></div>)}</div></div>}
 {step===2&&<div><h2 className="text-2xl font-black">DATA PERNIKAHAN</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><S label="Jenis permohonan" v={nikah.jenis_permohonan} set={setN("jenis_permohonan")} values={["NIKAH","TALAK","CERAI","RUJUK"]}/>{nikah.jenis_permohonan==="NIKAH"?<><F label="Hari akad"><input className={css} value={nikah.hari_akad} readOnly aria-readonly="true"/><small className="mt-1 block text-slate-600">Hari akad otomatis menyesuaikan tanggal yang dipilih.</small></F><I label="Tanggal akad" type="date" v={nikah.tanggal_akad} set={setN("tanggal_akad")}/><I label="Jam akad" type="time" v={nikah.jam_akad} set={setN("jam_akad")}/><I label="Tempat akad" v={nikah.tempat_akad} set={setN("tempat_akad")}/><I label="KUA tujuan" v={nikah.kua_tujuan} set={setN("kua_tujuan")}/><I label="Mas kawin" v={nikah.mas_kawin} set={setN("mas_kawin")}/><S label="Cara pembayaran mas kawin" v={nikah.cara_pembayaran_mas_kawin} set={setN("cara_pembayaran_mas_kawin")} values={["TUNAI","HUTANG"]}/><label><input type="checkbox" checked={nikah.membutuhkan_isbat} onChange={e=>setNikah({...nikah,membutuhkan_isbat:e.target.checked})}/> Membutuhkan N3 untuk isbat</label></>:<p>Form khusus saat ini tersedia untuk NIKAH.</p>}</div></div>}
 {step===3&&<div><h2 className="text-2xl font-black">DATA PASANGAN</h2><p className="my-4 rounded-xl bg-amber-50 p-3 font-bold">Lookup profil warga lain tidak dibuka demi ownership/privacy. Isi data pasangan.</p><Person data={pasangan} set={setPasangan}/></div>}
 {step===4&&<div className="space-y-4"><h2 className="text-2xl font-black">DATA ORANG TUA / WALI</h2><Parent title="AYAH" data={ayah} set={setAyah}/><Parent title="IBU" data={ibu} set={setIbu}/><section className="rounded-3xl border p-5"><h3 className="text-xl font-black">WALI NIKAH</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><I label="Nama lengkap" v={wali.nama_lengkap} set={setW("nama_lengkap")}/><I label="NIK" optional v={wali.nik} set={setW("nik")}/><I label="Hubungan dengan calon pengantin" v={wali.hubungan} set={setW("hubungan")}/><I label="Alamat" v={wali.alamat} set={setW("alamat")}/><I label="Nomor HP" optional v={wali.nomor_hp} set={setW("nomor_hp")}/></div></section></div>}
  {step===5&&<div><h2 className="text-2xl font-black">DOKUMEN PENDUKUNG</h2><p>Foto otomatis diproses maksimal 1 MB dan tetap memakai upload existing.</p>{berkas.map((x,i)=><section key={x.jenis} className="mt-3 rounded-xl border p-4"><b>{x.jenis} — {x.wajib?"WAJIB":"OPSIONAL"}</b><div className="mt-3 flex flex-wrap gap-2"><button type="button" className="rounded-xl bg-gov-900 px-4 py-3 font-black text-white" onClick={()=>cameraInputs.current[i]?.click()}>📷 AMBIL FOTO</button><button type="button" className="rounded-xl border px-4 py-3 font-black" onClick={()=>fileInputs.current[i]?.click()}>📁 PILIH FILE</button></div><input ref={el=>{cameraInputs.current[i]=el}} className="hidden" type="file" accept="image/*" capture="environment" onChange={e=>void file(i,e)}/><input ref={el=>{fileInputs.current[i]=el}} className="hidden" type="file" accept="application/pdf,image/jpeg,image/jpg,image/png,image/webp" onChange={e=>void file(i,e)}/>{x.processing&&<p className="mt-3 font-bold">Memproses foto...</p>}{x.file&&!x.processing&&<div className="mt-3 flex items-center gap-3"><b>✓ FILE SIAP</b>{x.preview&&<img src={x.preview} alt={`Preview ${x.jenis}`} className="h-14 w-20 rounded object-cover"/>}<span>{x.file.name} — {Math.ceil(x.file.size/1024)} KB / 1 MB</span></div>}{x.error&&<p className="mt-3 font-bold text-red-700">{x.error}</p>}</section>)}</div>}
 {step===6&&<div><h2 className="text-2xl font-black">PERNYATAAN & TANDA TANGAN</h2><p className="my-4 rounded-xl bg-slate-50 p-4">“{statement}”</p><label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Consent dan tanggung jawab data</label><div className="mt-4 grid gap-3 md:grid-cols-2">{["CALON ISTRI","CALON SUAMI","AYAH","IBU","WALI"].map(x=><div className="rounded-xl border p-3" key={x}><b>{x}</b><p>BELUM DITANDATANGANI</p><button disabled title="ElectronicSignatureProvider belum dikonfigurasi">Tanda tangan via HP/laptop</button></div>)}<div className="rounded-xl border p-3"><b>e-Meterai</b><p>BELUM DIGUNAKAN</p></div></div></div>}
  {step===7&&<div className="space-y-5 overflow-x-hidden"><div><h2 className="text-2xl font-black sm:text-3xl">REVIEW PENGAJUAN</h2><p className="mt-2 text-sm font-bold text-slate-600">Periksa kembali seluruh data sebelum pengajuan dikirim.</p><div className="mt-4 rounded-2xl bg-gov-50 p-4"><p className="text-xs font-black uppercase text-slate-500">Layanan</p><p className="mt-1 break-words font-black">{MARRIAGE_SERVICE_NAME}</p><p className="mt-3 text-xs font-black uppercase text-slate-500">Status</p><p className="mt-1 font-black text-emerald-700">SIAP DIAJUKAN</p></div></div>
  <div className="grid gap-5 lg:grid-cols-2"><ReviewCard title="DATA PEMOHON" step={1} edit={setStep}><ReviewRows rows={[["Nama",profile?.nama_lengkap],["NIK",profile?.nik],["Agama",profile?.agama],["Alamat",profile?.alamat]]}/></ReviewCard><ReviewCard title="DATA PERNIKAHAN" step={2} edit={setStep}><ReviewRows rows={[["Jenis permohonan",nikah.jenis_permohonan],["Tanggal akad",nikah.tanggal_akad],["Hari akad",nikah.hari_akad],["Jam akad",nikah.jam_akad],["Tempat akad",nikah.tempat_akad],["KUA tujuan",nikah.kua_tujuan],["Mas kawin",nikah.mas_kawin]]}/></ReviewCard><ReviewCard title="CALON PASANGAN" step={3} edit={setStep}><ReviewRows rows={[["Nama",pasangan.nama_lengkap],["NIK",pasangan.nik],["Jenis kelamin",pasangan.jenis_kelamin],["Tempat/Tanggal lahir",`${pasangan.tempat_lahir||"-"} / ${pasangan.tanggal_lahir||"-"}`],["Agama",pasangan.agama],["Pekerjaan",pasangan.pekerjaan],["Alamat",pasangan.alamat]]}/></ReviewCard>{[["AYAH",ayah],["IBU",ibu],["WALI",wali]].map(([title,data])=><ReviewCard key={title as string} title={title as string} step={4} edit={setStep}><ReviewRows rows={title==="WALI"?[["Nama",(data as Data).nama_lengkap],["Hubungan",(data as Data).hubungan],["Alamat",(data as Data).alamat]]:[["Nama",(data as Data).nama_lengkap],["NIK",(data as Data).nik],["Status",(data as Data).status],["Pekerjaan",(data as Data).pekerjaan]]}/></ReviewCard>)}</div>
  <ReviewCard title="DOKUMEN PENDUKUNG" step={5} edit={setStep} wide><div className="space-y-2">{berkas.map(x=><div key={x.jenis} className="flex min-w-0 items-center gap-2 text-sm font-bold"><span className={x.file?"text-emerald-700":"text-slate-500"}>{x.file?"✓":"○"}</span><span className="min-w-0 break-words">{x.jenis} — {x.file?`tersedia — ${Math.ceil(x.file.size/1024)} KB — ${x.file.name}`:"belum tersedia"}</span></div>)}</div></ReviewCard>
  <ReviewCard title="PERNYATAAN WARGA" step={6} edit={setStep} wide><p className="whitespace-pre-wrap break-words rounded-xl bg-slate-50 p-4 text-sm leading-7">{statement}</p><p className={`mt-3 font-black ${consent?"text-emerald-700":"text-amber-700"}`}>{consent?"✓ Pernyataan disetujui":"⚠ Belum disetujui"}</p></ReviewCard><ReviewCard title="TANDA TANGAN" step={6} edit={setStep} wide><div className="grid gap-2 sm:grid-cols-2">{["Calon Istri","Calon Suami","Ayah","Ibu","Wali"].map(x=><p key={x} className="rounded-xl bg-slate-50 p-3 text-sm font-bold">{x}<br/><span className="text-slate-600">BELUM DITANDATANGANI</span></p>)}</div></ReviewCard><ReviewCard title="METERAI" wide><p className="font-black">BELUM DIGUNAKAN</p><p className="mt-2 text-sm font-bold text-slate-600">Meterai elektronik akan diproses melalui provider resmi apabila telah tersedia.</p></ReviewCard><section className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="text-lg font-black">CHECKLIST PENGAJUAN</h3><div className="mt-3 grid gap-2 text-sm font-bold sm:grid-cols-2">{[["Data pemohon",Boolean(profile?.nik)],["Data pernikahan",Boolean(nikah.tanggal_akad&&nikah.kua_tujuan)],["Data pasangan",Boolean(pasangan.nama_lengkap)],["Data orang tua/wali",Boolean(ayah.nama_lengkap||ibu.nama_lengkap||wali.nama_lengkap)],["Dokumen pendukung",!berkas.some(x=>x.wajib&&!x.file)],["Pernyataan",consent],["Persetujuan",consent]].map(([x,ok])=><p key={x as string} className={(ok as boolean)?"text-emerald-700":"text-amber-700"}>{(ok as boolean)?"✓":"⚠"} {x} — {(ok as boolean)?"Lengkap":"Belum lengkap"}</p>)}</div></section><aside className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold"><b>PENTING</b><p className="mt-1">Pastikan seluruh data sudah benar. Setelah pengajuan dikirim, data akan diproses sesuai tahapan pelayanan.</p></aside></div>}
 {step===8&&<div className="text-center"><h2 className="text-3xl font-black">AJUKAN</h2><p>Petugas → Seklur → Lurah → TTE Lurah → QR/BARCODE → PDF FINAL</p><Button type="button" disabled={busy} onClick={submit} className="mt-5">{busy?"Mengirim...":"YA, AJUKAN"}</Button></div>}
 <div className="mt-7 flex justify-between border-t pt-5">{step>1?<Button type="button" variant="glass" onClick={()=>setStep(step-1)}>← KEMBALI</Button>:<span/>}{step<8&&<Button type="button" onClick={()=>valid(step)&&setStep(step+1)}>LANJUT →</Button>}</div></section></main>;
}