import Link from "next/link";
import { Activity, CheckCircle2, ClipboardCheck, FileText, Send, User, XCircle } from "lucide-react";
type Row = Record<string, any>;
type Profile = { full_name?: string | null; username?: string | null };
const names: Record<string, string> = { SELESAI: "Selesai", DISETUJUI: "Selesai", DITOLAK: "Ditolak", DIBATALKAN: "Ditolak", DIPROSES: "Diproses" };
const person = (r: Row) => r.nama_pemohon ?? r.nama_lengkap ?? r.nama ?? r.pemohon_nama ?? "-";
const service = (r: Row) => r.layanan?.nama ?? r.jenis_surat ?? r.layanan_nama ?? "-";
const state = (r: Row) => String(r.status ?? r.workflow_status ?? r.active_stage?.status ?? "DIPROSES").toUpperCase().replace(/\s+/g, "_");
const date = (v: unknown) => { const d = new Date(String(v ?? "")); return Number.isNaN(d.getTime()) ? "-" : d.toLocaleDateString("id-ID", { day: "2-digit", month: "short", year: "numeric" }); };
function Card({ title, value, icon: Icon, href, alert }: { title: string; value: number; icon: typeof User; href?: string; alert?: boolean }) { const content = <div className={`relative min-h-[104px] rounded-2xl border bg-white p-4 shadow-sm ${alert ? "border-amber-300 ring-1 ring-amber-100" : "border-slate-200"}`}><Icon size={19} className="text-emerald-700" /><p className="mt-3 text-2xl font-black text-gov-950">{value}</p><p className="text-xs font-bold text-slate-500">{title}</p>{alert && <span className="absolute right-3 top-3 rounded-full bg-amber-400 px-2 py-0.5 text-[10px] font-black">BARU</span>}</div>; return href ? <Link href={href}>{content}</Link> : content; }
export function PetugasDashboardCompact({ rows, wargaRows, stats, profile, role }: { rows: Row[]; wargaRows: Row[]; stats: Row; profile: Profile; role: string }) {
    const warga = stats.warga ?? { menunggu: wargaRows.length, terverifikasi: 0, ditolak: 0, total: wargaRows.length };
    const pelayanan = stats.pelayanan ?? { masuk: rows.length, proses: rows.length, selesai: 0, ditolak: 0 };
    const trend = (stats.service_trend ?? []) as Array<{ label: string; total: number }>;
    const latest = [...rows].sort((a, b) => new Date(String(b.updated_at ?? b.created_at ?? 0)).getTime() - new Date(String(a.updated_at ?? a.created_at ?? 0)).getTime()).slice(0, 5);
    const max = Math.max(1, ...trend.map((x) => x.total));
    return <div className="mx-auto max-w-7xl space-y-5"><div><p className="text-sm font-bold text-emerald-700">Ringkasan pekerjaan · {role === "kepala_seksi" ? "Kasi" : role === "lurah" ? "Lurah" : profile.full_name ?? profile.username ?? "Petugas"}</p><h1 className="text-2xl font-black tracking-tight text-gov-950 md:text-3xl">Dashboard Petugas</h1></div>
        <section><div className="mb-2 flex justify-between"><h2 className="font-black text-gov-950">Verifikasi Akun Warga</h2><Link href="/petugas/verifikasi-warga" className="text-xs font-black text-emerald-700">Buka verifikasi →</Link></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Card title="Menunggu Verifikasi" value={warga.menunggu} icon={ClipboardCheck} href="/petugas/verifikasi-warga" alert={warga.menunggu > 0} /><Card title="Terverifikasi" value={warga.terverifikasi} icon={CheckCircle2} /><Card title="Ditolak" value={warga.ditolak} icon={XCircle} /><Card title="Total Akun Warga" value={warga.total} icon={User} /></div></section>
        <section><h2 className="mb-2 font-black text-gov-950">Pengajuan Pelayanan</h2><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Card title="Pengajuan Masuk" value={pelayanan.masuk} icon={Send} href={role === "kepala_seksi" ? "/petugas/tugas" : undefined} alert={role === "kepala_seksi" && pelayanan.masuk > 0} /><Card title="Dalam Proses" value={pelayanan.proses} icon={Activity} /><Card title="Selesai" value={pelayanan.selesai} icon={CheckCircle2} /><Card title="Ditolak" value={pelayanan.ditolak} icon={XCircle} /></div></section>
        <section className="grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="font-black text-gov-950">Grafik Pelayanan</h2><p className="text-xs font-bold text-slate-500">Jumlah pengajuan per bulan</p><div className="mt-5 flex h-36 items-end gap-2 sm:gap-4">{trend.map((x) => <div key={`${x.label}-${x.total}`} className="flex h-full flex-1 flex-col items-center justify-end"><span className="text-[11px] font-black text-slate-500">{x.total}</span><div className="w-full max-w-12 rounded-t-lg bg-gradient-to-t from-emerald-800 to-emerald-300" style={{ height: `${Math.max(4, x.total / max * 100)}%` }} /><span className="mt-2 text-[11px] font-bold text-slate-500">{x.label}</span></div>)}</div></div><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="font-black text-gov-950">Status Pengajuan</h2><div className="mt-5 space-y-4">{[["Diproses", pelayanan.proses, "bg-amber-400"], ["Selesai", pelayanan.selesai, "bg-emerald-500"], ["Ditolak", pelayanan.ditolak, "bg-rose-500"]].map(([title, value, color]) => <div key={String(title)}><div className="flex justify-between text-sm font-black"><span>{title}</span><span>{value}</span></div><div className="mt-1 h-2 rounded-full bg-slate-100"><div className={`h-2 rounded-full ${color}`} style={{ width: `${Number(value) ? 55 : 0}%` }} /></div></div>)}</div></div></section>
        <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between p-4"><h2 className="font-black text-gov-950">Aktivitas Terbaru</h2><Link href="/petugas/tugas" className="text-xs font-black text-emerald-700">Lihat semua →</Link></div><div className="divide-y">{latest.length ? latest.map((r) => <Link href={`/petugas/pengajuan/${r.id}`} key={r.id} className="grid gap-1 px-4 py-3 hover:bg-emerald-50 sm:grid-cols-[1.1fr_1fr_1fr_auto] sm:items-center"><span className="truncate text-sm font-black">{r.nomor_pengajuan ?? "Pengajuan"}</span><span className="truncate text-xs font-bold text-slate-600">{person(r)}</span><span className="truncate text-xs font-bold text-slate-500">{service(r)}</span><span className="text-xs font-black text-emerald-700">{names[state(r)] ?? state(r)} · {date(r.updated_at ?? r.created_at)}</span></Link>) : <p className="p-8 text-center text-sm font-bold text-slate-500">Belum ada aktivitas.</p>}</div></section>
    </div>;
}