"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Bell, FileText, FolderOpen, Heart, Settings, UserRound } from "lucide-react";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { useWargaAuth } from "@/components/auth/warga-auth-provider";
import { isVerified, type WargaProfile } from "@/services/warga-auth.service";
import { getMyPengajuan, type WargaPengajuan } from "@/services/warga-pengajuan.service";

const cards = [{ id: "pengajuan", title: "📄 Pengajuan Saya", icon: FileText }, { id: "notifikasi", title: "📢 Notifikasi", icon: Bell }, { id: "profil", title: "👤 Profil Saya", icon: UserRound }, { id: "favorit", title: "❤️ Favorit", icon: Heart }, { id: "dokumen", title: "📂 Dokumen Saya", icon: FolderOpen }, { id: "pengaturan", title: "⚙ Pengaturan", icon: Settings }];

export default function DashboardPage() {
    const router = useRouter();
    const { user, profile, loading } = useWargaAuth();
    const [items, setItems] = useState<WargaPengajuan[]>([]);
    const [fetching, setFetching] = useState(false);
    useEffect(() => { if (!loading && !user) router.push("/login"); }, [loading, user, router]);
    useEffect(() => { if (!user || !profile) return; void (async () => { try { setFetching(true); setItems(await getMyPengajuan()); } catch (error) { console.error(error); } finally { setFetching(false); } })(); }, [user, profile]);
    if (loading || !user) return <main className="min-h-screen bg-[#F7F9FC] p-10 font-black text-gov-950">Memuat dashboard...</main>;
    if (!isVerified(profile)) return <main className="min-h-screen bg-[#F7F9FC] px-5 py-16 sm:px-10 lg:px-20"><section className="mx-auto max-w-2xl rounded-[32px] border border-white bg-white/85 p-8 text-center shadow-soft"><h1 className="text-3xl font-black text-gov-950">Akun Anda belum diverifikasi</h1><p className="mt-4 leading-7 text-slate-600">Petugas Kelurahan Tamansari sedang memverifikasi data NIK, KK, dan profil Anda.</p><div className="mt-6 flex justify-center"><Button type="button" variant="gold" href="/verify">Cek Status Verifikasi</Button></div></section></main>;
    return <main className="min-h-screen bg-[#F7F9FC] px-5 py-16 text-slate-800 sm:px-10 lg:px-20"><section className="mx-auto max-w-[1440px]"><div className="rounded-[32px] bg-[linear-gradient(135deg,#0B2C6A,#071a33)] p-8 text-white shadow-[0_24px_80px_rgba(11,44,106,.18)]"><p className="text-accent-200 font-black uppercase tracking-[.2em]">Dashboard Saya</p><h1 className="mt-4 text-4xl font-black">Halo, {profile?.nama_lengkap ?? "Warga Tamansari"}</h1><p className="mt-3 text-white/75">Selamat datang kembali.</p></div><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{cards.map(({ id, title, icon: Icon }, i) => <motion.section id={id} key={id} initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * .04 }} whileHover={{ scale: 1.02 }} className="rounded-[24px] border border-white bg-white/85 p-6 shadow-soft backdrop-blur"><Icon className="text-accent-500" /><h2 className="mt-4 text-2xl font-black text-gov-950">{title}</h2>{id === "pengajuan" ? <SubmissionList items={items} fetching={fetching} /> : id === "profil" ? (profile ? <ProfileBlock profile={profile} /> : <EmptyProfile />) : id === "dokumen" ? <Documents items={items} /> : <p className="mt-4 leading-7 text-slate-600">Data akan terhubung dengan aktivitas layanan warga secara realtime.</p>}</motion.section>)}</div></section></main>;
}

function formatStatus(status?: string | null) { return status || "Menunggu Verifikasi"; }
function latestStage(item: WargaPengajuan) { const latest = item.tracking_pengajuan?.at(-1); return latest?.petugas || latest?.status || latest?.keterangan || "Pengajuan Dikirim"; }
function formatDate(value?: string | null) { return value ? new Date(value).toLocaleDateString("id-ID", { day: "2-digit", month: "long", year: "numeric" }) : "-"; }

function SubmissionList({ items, fetching }: { items: WargaPengajuan[]; fetching: boolean }) {
    if (fetching) return <p className="mt-4 font-bold text-slate-500">Memuat pengajuan...</p>;
    if (items.length === 0) return <div className="mt-4 space-y-4"><p className="font-bold text-slate-500">Belum ada pengajuan.</p><Button type="button" variant="gold" href="/surat-online/ajukan">+ Ajukan Layanan</Button></div>;
    return <div className="mt-4 space-y-4">{items.slice(0, 3).map((item) => <div key={item.id} className="rounded-2xl bg-gov-50 p-4"><p className="font-black text-gov-950">{item.nomor_pengajuan}</p><p className="text-sm font-bold text-slate-600">{item.layanan?.nama ?? "Nama layanan tidak tersedia"}</p>{item.keperluan ? <p className="mt-1 text-sm text-slate-600">{item.keperluan}</p> : null}<p className="mt-3 inline-flex rounded-full bg-amber-100 px-3 py-1 text-xs font-black uppercase tracking-wide text-amber-700">{formatStatus(item.status)}</p><p className="mt-3 text-sm font-bold text-gov-950">Tahap: {latestStage(item)}</p><p className="mt-1 text-sm font-bold text-slate-500">{formatDate(item.created_at)}</p><Button type="button" variant="glass" className="mt-4" href={`/dashboard/pengajuan/${item.id}`}>Lihat Detail</Button></div>)}<Button type="button" variant="gold" href="/dashboard/pengajuan">Lihat Semua Pengajuan</Button></div>;
}
function ProfileBlock({ profile }: { profile: WargaProfile }) { return <div className="mt-4 space-y-2 text-sm font-bold text-slate-700"><p>Nama: {profile.nama_lengkap}</p><p>NIK: {profile.nik}</p><p>Email: {profile.email}</p><p>WhatsApp: {profile.nomor_whatsapp}</p><p>Alamat: {profile.alamat}, RT {profile.rt}/RW {profile.rw}</p><p>{profile.kelurahan}, {profile.kecamatan}</p><Button type="button" variant="glass" href="/dashboard#profil">Edit Profil</Button></div>; }
function EmptyProfile() { const handleRefresh = () => window.location.reload(); return <div className="mt-5 rounded-[24px] bg-white p-6 text-center shadow-[0_18px_50px_rgba(11,44,106,.10)] ring-1 ring-gov-100/70"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-[24px] bg-[linear-gradient(135deg,#0B2C6A,#071a33)] shadow-[0_14px_34px_rgba(11,44,106,.22)]"><UserRound className="h-11 w-11 text-accent-400" aria-hidden="true" /></div><h3 className="mt-6 text-2xl font-black text-gov-950">Profil Belum Tersedia</h3><p className="mt-3 leading-7 text-slate-600">Data profil warga belum ditemukan. Silakan lengkapi data atau login kembali.</p><div className="mt-6 flex flex-col justify-center gap-3 sm:flex-row"><Button type="button" variant="gold" onClick={handleRefresh}>Refresh Data</Button><Button type="button" variant="glass" href="/">Kembali ke Beranda</Button></div></div>; }
function Documents({ items }: { items: WargaPengajuan[] }) { const docs = items.flatMap((item) => item.dokumen_pengajuan ?? []); if (!docs.length) return <p className="mt-4 font-bold text-slate-500">Belum ada dokumen.</p>; return <div className="mt-4 grid gap-2">{docs.map((doc, index) => <a key={`${doc.url_file}-${index}`} href={doc.url_file ?? "#"} target="_blank" rel="noreferrer" className="rounded-xl bg-gov-50 px-3 py-2 text-sm font-bold text-gov-950 underline">{doc.jenis ?? doc.nama_file ?? "Dokumen"}</a>)}</div>; }